language: elixir
env:
  global:
    - MIX_ENV=test
jobs:
  include:
    - elixir: '1.3'
      otp_release: '19.3'
      script: mix test
    - elixir: '1.4'
      otp_release: '19.3'
      script: mix test
    - elixir: '1.5'
      otp_release: '20.3'
      script: mix test
    - elixir: '1.6'
      otp_release: '20.3'
      script: mix test
    - elixir: '1.7'
      otp_release: '22.2'
      script: mix test
    - elixir: '1.8'
      otp_release: '22.2'
      script: mix test
    - elixir: '1.9'
      otp_release: '22.2'
      script: mix test
    - elixir: '1.10'
      otp_release: '22.2'
      script: mix test
sudo: false # to use faster container based build environment
cache:
  directories:
    - _build
    - deps
